### ISSUE TITLE
Type hinting format requires Python 3.10

### ISSUE THREAD

**Issue by gaddman** [arussu/mon2pcap#1]
Firstly, great tool so thanks very much!
Tried to install and run under Python 3.9 and received this error:
```
$ mon2pcap
Traceback (most recent call last):
  File "/home/myuser/pyvenv/bin/mon2pcap", line 5, in <module>
    from mon2pcap.console import run
  File "/home/myuser/pyvenv/lib64/python3.9/site-packages/mon2pcap/__init__.py", line 7, in <module>
    from .mon2pcap import Mon2Pcap
  File "/home/myuser/pyvenv/lib64/python3.9/site-packages/mon2pcap/mon2pcap.py", line 12, in <module>
    from .constants import STATS, protocol_mapping
  File "/home/myuser/pyvenv/lib64/python3.9/site-packages/mon2pcap/constants.py", line 55, in <module>
    def protocol_mapping(eventid: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
That's because the type hinting format you're using isn't supported until Python 3.10, see [What’s New In Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#pep-604-new-type-union-operator).

Rather than incrementing the pre-requisite Python version, you could use the older, pre 3.10, format of type hinting, eg
```python
from typing import Optional
def protocol_mapping(eventid: str) -> Optional[str]:
```

**Comment by arussu** [comment]
Hi [Christopher](https://github.com/gaddman),

Indeed. 
Should be fixed now.

Thanks
